.ssh: &ssh
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | ssh-add -

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - make test

deploy to staging:
  stage: deploy
  environment:
    name: staging
  only:
    - master
  <<: *ssh
  script:
    - echo "Deploying to staging"
    - php deployer.phar --version
    - php deployer.phar deploy --revision $CI_COMMIT_SHA staging -vvv

deploy to production:
  stage: deploy
  environment:
    name: production
  when: manual
  only:
    - master
  <<: *ssh
  script:
    - echo "Deploying to production"
    - php deployer.phar --version
    - php deployer.phar deploy --revision $CI_COMMIT_SHA production -vvv
