version: '3.6'
services:
  silverstripe:
    build:
      context: .
      dockerfile: Dockerfile
      target: php-fpm-dev
    working_dir: /app
    env_file:
      - .env.docker
    volumes:
      - .:/app
    tty: true

  nginx:
    image: nginx:1.15
    ports:
      - 50080:80
    volumes:
      - ./dev/docker/nginx/development.conf:/etc/nginx/conf.d/default.conf
      - .:/app

  mariadb:
    image: mariadb:10.1
    restart: always
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: silverstripe
    ports:
      - 50336:3306

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 50025:8025

volumes:
  mariadb-volume:
